PREFIX ab: <http://learningsparql.com/ns/addressbook#>
#Using files ex072.ttl, ex073.ttl, ex368 

SELECT ?first ?last ?courseName ?course

 WHERE {

     ?person ab:firstName ?first;
             ab:lastName  ?last;
             ab:takingCourse ?course . 

     ?course ab:courseTitle ?courseName .         


 }