PREFIX ex: <http://www.example.org/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?mount ?size
   
   WHERE {
       

       ?mount rdf:type  ex:Mountain.
       ?mount ex:hasHeightInMeter ?size.
       
   }